#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

j="0"
while [ $j -le 12 ]
do

echo "Hour: $j"
i="1"
while [ $i -le 59 ]
do

echo "$i"
i=$((i+1))
done
j=$((j+1))
done
